# Generated by Django 6.0.3 on 2026-03-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualification", "0001_initial"),
        ("universities", "0002_university_university_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="university",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualifications",
                to="universities.university",
            ),
            preserve_default=False,
        ),
    ]
