# Generated by Django 6.0.3 on 2026-04-10 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualification", "0002_qualification_university"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThroughputStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cohort_year",
                    models.PositiveIntegerField(
                        help_text="The year this group of students started"
                    ),
                ),
                (
                    "total_intake",
                    models.PositiveIntegerField(
                        help_text="Total number of students who enrolled"
                    ),
                ),
                (
                    "graduated_n_plus_2",
                    models.PositiveIntegerField(
                        help_text="Students who finished in N+2 years (CHE Standard)"
                    ),
                ),
                (
                    "is_faculty_level",
                    models.BooleanField(
                        default=False,
                        help_text="Check this if data is for the whole Faculty (e.g., SET) rather than the specific degree.",
                    ),
                ),
                (
                    "qualification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="qualification.qualification",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Throughput Stats",
            },
        ),
    ]
