# Generated by Django 6.0.3 on 2026-03-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="university_code",
            field=models.CharField(default="N/A", max_length=10),
            preserve_default=False,
        ),
    ]
