# Generated by Django 6.0.3 on 2026-03-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
        ("qualification", "0002_qualification_university"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="industry",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name="career",
            name="qualification",
        ),
        migrations.AddField(
            model_name="career",
            name="qualification",
            field=models.ManyToManyField(
                related_name="career", to="qualification.qualification"
            ),
        ),
    ]
