# Generated by Django 6.0.3 on 2026-04-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("universities", "0002_university_university_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bursary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("ENG", "Engineering"),
                            ("EDU", "Education"),
                            ("MED", "Medicine"),
                            ("COM", "Commerce"),
                            ("LAW", "Law"),
                        ],
                        default="ALL",
                        max_length=3,
                    ),
                ),
                ("bursary_name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                (
                    "fields_of_study",
                    models.CharField(
                        help_text="e.g. Engineering, Accounting, IT", max_length=255
                    ),
                ),
                ("application_link", models.URLField()),
                ("closing_date", models.DateField(blank=True, null=True)),
                (
                    "applicable_universities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave blank if it applies to all universities",
                        to="universities.university",
                    ),
                ),
            ],
        ),
    ]
